title: Muspi Merol's personal index
email: 1797936329@qq.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到Muspi Merol的个人索引页面
baseurl: "/"
url: "https://cnseniorious000.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# gitee_username: Seniorious000
github_username: CNSeniorious000

# Build settings
theme: minima

plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
