title          : Muspi Merol
description    : Muspi Merol's personal index
show_downloads : no

github:
  owner_name      : Muspi Merol
  owner_url       : https://github.com/CNSeniorious000
  repository_name : CNSeniorious000.github.io
  reposito+ry_url : https://github.com/CNSeniorious000/CNSeniorious000.github.io
  is_project_page : yes

theme   : jekyll-theme-cayman
plugins : [jekyll-feed]
